# Generated by Django 4.0.4 on 2022-05-03 22:07

from django.db import migrations, models
import django.db.models.deletion
import pancakes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=254)),
                ('cooking_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pancakes.models.recipe_image_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.IntegerField()),
                ('description', models.CharField(max_length=8191)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipeimage')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipecategory')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(through='pancakes.RecipeRecipeCategory', to='pancakes.recipecategory'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipeimage'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('unit', models.CharField(max_length=254)),
                ('amount', models.CharField(max_length=254)),
                ('recipe_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pancakes.recipestage')),
            ],
        ),
    ]
