# Generated by Django 4.0.3 on 2022-06-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pancakes', '0002_rename_stage_object_recipestagerecipeingredient_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=200)),
                ('facebook_link', models.URLField(default='')),
                ('instagram_link', models.URLField(default='')),
                ('twitter_link', models.URLField(default='')),
                ('youtube_link', models.URLField(default='')),
                ('profile_pic', models.ImageField(blank=True, default='default/default.PNG', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
